/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    id("org.springframework.boot") version "3.1.5"
    id("io.spring.dependency-management") version "1.1.3"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.org.springframework.data.spring.data.elasticsearch)
    implementation(libs.com.opencsv.opencsv)
    implementation(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    implementation(libs.commons.io.commons.io)
    implementation(libs.org.jsoup.jsoup)
    implementation(libs.javax.xml.bind.jaxb.api)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.restdocs.spring.restdocs.mockmvc)
    testImplementation("com.h2database:h2:2.2.224")
}

group = "com.tech-blog-finder"
version = "0.0.1-SNAPSHOT"
description = "api"

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

tasks.withType<Test>() {
    useJUnitPlatform()
}