FROM eclipse-temurin:17
ARG DB_URL
ARG DB_PORT
ARG DB_SCHEMA
ARG DB_USERNAME
ARG DB_PASSWORD
ARG SERVER_PORT
ARG ELASTICSEARCH_URL
ARG JAR_FILE=build/libs/*.jar
ENV DB_URL=${DB_URL} \
    DB_PORT=${DB_PORT} \
    DB_SCHEMA=${DB_SCHEMA} \
    DB_USERNAME=${DB_USERNAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    SERVER_PORT=${SERVER_PORT} \
    ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 80