version: '3.7'

networks:
  tickle-network:
    driver: bridge

services:
  database:
    container_name: mysql
    image: mysql:8.0.22
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${DB_DATA_PATH}/mysql/data:/var/lib/mysql
    networks:
      - tickle-network
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - ${ES_DATA_PATH}/elasticsearch/data:/var/lib/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
    networks:
      - tickle-network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    networks:
      - tickle-network